package dungeonforge.events;

public enum EventType {
    DAMAGE_DEALT,
    DAMAGE_TAKEN,
    MONSTER_DIED,
    MONSTER_FLED,
    MONSTER_HEALED,
    STRATEGY_CHANGED,
    XP_GAINED,
    GOLD_GAINED,
    LEVEL_ENTERED,
    ROOM_CLEARED,
    PLAYER_DIED,
    DELVE_SURVIVED,
    MESSAGE
}
